name: Deploy
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # 用于 Deno Deploy 身份认证
      contents: read # 用于克隆仓库
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      # 没有使用 npm？将 `npm ci` 更改为 `yarn install` 或 `pnpm i`
      - name: Install dependencies
        run: npm ci
      # 没有使用 npm？将 `npm run build` 更改为 `yarn build` 或 `pnpm run build`
      - name: Build Astro
        run: npm run build
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: side7 # TODO：替换为 Deno Deploy 项目名称
          entrypoint: jsr:@std/http/file-server
          root: dist